### ISSUE TITLE
Problems restoring from seed

### ISSUE THREAD

**Issue by ElVrana** [darkwallet/darkwallet#246]
Hello colleagues,

I would kindly ask for your help on how to restore DarkWallet account. Somehow I managed to clean my computer in a way that DarkWallet didn't worked anymore...

What I did is restored it with a words that you have to remember when you first create your wallet (restore from seed). The problem that I have now is that all the money is gone when I log in into my existing - restored account!

Could somebody please help me with some ideas what else I need to do in order to get my BTC back?
In return I'm offering a BTC reward.

Thaaaanks in advace!

**Comment by amingilani** [comment]
Free stuff!! I can help! :dancer: okay, what version did you upgrade from? Or were you on the latest build before and after?

**Comment by ElVrana** [comment]
Hey amingilani,

To clear things out, I did not make any upgrades. I was using ver. 0.8.0, but I accidentally deleted / moved / renamed (don't remember exactly) folder files of DarkWallet - after that I was unable to log in into my wallet.

What I did is deleted DarkWallet from my Chrome and installed it again from the beginning. I went to create new wallet and use option to restore from seed. I key entered words that I was requested and successfully restored wallet (at least it looks like that). But...

...there is no money, no history in that restored wallet. What I would like to know is how to proceed in order to get my money back that is waiting for me on some BTC address???

Thanks!

**Comment by sembrestels** [comment]
Did you used the scanning tool? It is at **Settings > Tools > Scan**. This should solve the issue, I think.

**Comment by ElVrana** [comment]
Hey sembrestels,

Yes I did try this...but it still does not find any BTC, history, nothing :(.
If you have any other idea please let me know...

Thanks in advance!

Regards

**Comment by ABISprotocol** [comment]
@ElVrana Just going on a hunch, have you tried an _earlier_ release of DW plus the steps already recommended (create new wallet, option to restore from seed, then settings - tools - scan)? Just wondering if that would work in your particular case.  https://wiki.unsystem.net/en/index.php/Darkwallet
Before you do that though check out the list of known issues for Alpha 8
here: https://wiki.unsystem.net/en/index.php/DarkWallet/Alpha8/KnownIssues
and here: https://github.com/darkwallet/darkwallet/issues

**Comment by ElVrana** [comment]
@ABISprotocol I did try this as well but...nothing :( As for me goes I just can't find a way to do it. Anyone who wish to earn some €€€/$$$ feel free to contact me...I will share what you need with you in good faith that you are an honest person and will not rip me off in case that you will get my money back. In return you will get your share. I really don't have any other options at the moment :(

**Comment by miragecash** [comment]
Your money is not gone, but your transaction history might be. Use another new computer and install the Darkwallet. When setting up a new Darkwallet, it will ask you to either restore from seed (your 12 secret words that you wrote down when you set up the wallet) or start a new wallet. Choose "restore from seed". That should get your Bitcoins back. AFTER this, delete all your Darkwallet files on your old computer, uninstall Darkwallet on your old computer, and then reinstall Darkwallet on your original old computer. THEN, transfer your Bitcoins back from new computer to old original computer. 

The reason I suggested this procedure is because it sounds like you had corrupted the Darkwallet files on your old computer, "I accidentally deleted / moved / renamed (don't remember exactly) folder files of DarkWallet ".

You're welcome. BTW, do not send me bitcoins as a reward. However, please send the bitcoins to the Darkwallet project. Just send me a few millibits from the same address that you sent to the Darkwallet project with so I could verify that you donated to bitcoin project and smile in satisfaction.

**Comment by miragecash** [comment]
Webpage for donation to Dark Wallet Project: https://www.darkwallet.is/ . Bitcoin QR code is on the bottom. Do not donate to dufuses in chat room as they are not legit and are not affiliated with Dark Wallet Project in any way.

**Comment by ElVrana** [comment]
Hello miragecash,

Is it possible to contact you via private chanel / msg? Please let me know. 
Thanks!

Regards!

**Comment by caedesvvv** [comment]
Any luck?

**Comment by ElVrana** [comment]
Hmmm...NO :( Any idea?

V V sre., 27. jan. 2016 ob 13:32 je oseba caedesvvv <
notifications@github.com> napisala:

**Comment by grnqrtr** [comment]
@ElVrana Will you PM me on Reddit, I'd like to try to help if possible? Same username /u/grnqrtr

**Comment by ElVrana** [comment]
@grnqrtr Hey! Thank you - just sent you msg on Reddit - THAANKS!

**Comment by ElVrana** [comment]
@grnqrtr again I would like to thank you for helping me out - you truly are BTC problem solver :)

I don't know how you did it (many have tried) but you got my money back (after 2 years of trying)!!! I can't express how happy I am - once again many thanks! Your good work won't be forgotten.

**Comment by biorapid** [comment]
Just would like to second Elvrana's comment on grnqrtr.

Had looked at another thread of him helping someone and decided out of the blue to message him as I had bit coins stuck for almost a year now.
Within a day he has managed to get my £350 worth of BTC out and literally saved my day.

Made my day man!

**Comment by calhroub** [comment]
Hi. Is there any way this can work with a multi-sig address. My address starts with a '3' instead of a '1'. When I use the tool it keeps giving me addresses that start with a '1'...
Also when I try to export private key from Dark Wallet, after I put my password and address, it says "wallet not from this address". Any ideas, please?
Do you think I am lucky enough @grnqrtr ? Thanks.

UPDATE: with a lot of help from u/Deminero30 I managed to export private keys using chrome developer tools, but none of the exported private keys belong to the multi-sig address. Also, we managed to re-create the same multi-sig address to see what 3 stealth addresses were used to create the multi-sig, and we succeeded and determined that these 3 stealth addresses were used:
vJmxxrR2CRapWk83rQ4iZrigzvg9xrXw3kJvyiFJLcnKzQdDzQga2TNi77ZDSjJits65uidqZf5NBHqbFqPGAos4gjmRZ1eYRDey7V
vJmvtJv4BkMfuGbKqSqLXqMmsrDMLFZAt6B9ZsGwcEg884GSiRuaFxMRd8Twp7myvmCBhThSyVBY6fKjFivpa4NT9uVE71v2onFiqA
vJmz7VJN2NYv47SgeEz6XhCNJAzSeRB58cfr3v1LNXeP5Hxagz7Droxg9CsYoW2ZW6teiCKrg4pzptBXWmvYmrxcqBQztLJfPbLifx

An admin from another platform suggested that since the "unsystem" doesn't work anymore, I could try to connect to a different server or own server, or something like that, but he couldn't provide more info as he is a busy man... I have created https://www.reddit.com/r/Bitcoin/comments/8i1ev8/help_please_i_have_btc_stuck_in_dark_wallet_080/ to hopefully get some help from anyone. Any help would be greatly appreciated. Thanks.

**Comment by Danux187** [comment]
i dont know if someone can help me here but i have a little problem, i have sent to the webwallet of darkwallet.cc . I can log in but cant send any amount out of this account. Can somebody please help me here?

**Comment by jonathancross** [comment]
@Danux187 darkwallet.cc (or `darkwallet.co` for that matter) are separate from this project and likely scams that steal your money.  This repo is for the [original Dark Wallet](https://bitcoinmagazine.com/articles/dark-wallet-walkthrough-1414730735/) project from 2014 which is no longer maintained or being worked on.
