### ISSUE TITLE
Can't remove recipients in Send

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#52]
You can add them, but removal is possible only by deleting the address. There should be an option to delete lines. They persist even after navigating away from Send.

**Comment by caedesvvv** [comment]
+1

**Comment by sembrestels** [comment]
Should there be a button to restart send from, near Send button?

**Comment by leafcutterant** [comment]
Yeah, I see that as a good idea, a better name would be "Reset all fields". But the user should also be able to remove recipients one by one. e.g. a "+" and a "-" button at the end of each recipient row, this way user doesn't even have to go to advanced options to add and remove recipients.

Plus, I think fields should be reset upon navigating away from the Send menu, but that's more of a subjective issue. This would be beneficial from the perspective of not leaving any traces behind.

**Comment by caedesvvv** [comment]
this was solved not long ago so now you can remove lines from the advanced send

**Comment by leafcutterant** [comment]
Thanks! Now it works if you insert a valid address, but empty lines can't be removed. Could you please add the "X" button to every line (as the Scan QR code and Contact button)?

Also, the fields still don't reset when leaving the sending dialogue. I think it would be crucial not to leave traces behind.

**Comment by leafcutterant** [comment]
This is still an issue as of the most recent build, please **open it**.
